server {
    listen 80;
    server_name tmp.smoke.test-zone tmp.test;
    root "C:/Users/Administrator/Documents/panel-win/sites/tmp";
    access_log "C:/Users/Administrator/Documents/panel-win/pawon-data/logs/nginx/tmp.smoke.test-zone-access.log";
    error_log  "C:/Users/Administrator/Documents/panel-win/pawon-data/logs/nginx/tmp.smoke.test-zone-error.log";
    index index.php index.html;
    location / { try_files $uri $uri/ /index.php?$query_string; }
    location ~ \.php$ {
        try_files $fastcgi_script_name =404;
        include fastcgi_params;
        fastcgi_pass php_84_pool;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
